[package]
name = "InsideTheCurve"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.15", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
pyo3 = "0.24.2"
serde = { version = "1.0.228", features = ["derive"] }


